SAMPLE_LISTINGS = [
    {
        "source": "sample",
        "district": "朝阳区",
        "community": "望京西园",
        "rent_price": "6800元/月",
        "area": "62㎡",
        "house_type": "2室1厅",
        "orientation": "南北",
        "floor": "中楼层/18层",
        "tags": ["近地铁", "集中供暖", "整租"],
        "publish_time": "今天",
    },
    {
        "source": "sample",
        "district": "朝阳区",
        "community": "青年路小区",
        "rent_price": "5200元/月",
        "area": "48平米",
        "house_type": "1室1厅",
        "orientation": "南",
        "floor": "高楼层/21层",
        "tags": ["电梯房", "精装修"],
        "publish_time": "1天前",
    },
    {
        "source": "sample",
        "district": "海淀区",
        "community": "知春里",
        "rent_price": "7900元/月",
        "area": "70㎡",
        "house_type": "2室1厅",
        "orientation": "南",
        "floor": "低楼层/6层",
        "tags": ["近地铁", "学区周边"],
        "publish_time": "2天前",
    },
    {
        "source": "sample",
        "district": "海淀区",
        "community": "上地东里",
        "rent_price": "9800元/月",
        "area": "88㎡",
        "house_type": "3室1厅",
        "orientation": "南北",
        "floor": "中楼层/12层",
        "tags": ["整租", "拎包入住"],
        "publish_time": "今天",
    },
    {
        "source": "sample",
        "district": "西城区",
        "community": "广安门外大街",
        "rent_price": "9100元/月",
        "area": "63㎡",
        "house_type": "2室1厅",
        "orientation": "东南",
        "floor": "中楼层/16层",
        "tags": ["近地铁", "交通便利"],
        "publish_time": "3天前",
    },
    {
        "source": "sample",
        "district": "东城区",
        "community": "东四十条",
        "rent_price": "7600元/月",
        "area": "55㎡",
        "house_type": "1室1厅",
        "orientation": "南",
        "floor": "低楼层/6层",
        "tags": ["整租", "精装修"],
        "publish_time": "今天",
    },
    {
        "source": "sample",
        "district": "丰台区",
        "community": "方庄芳城园",
        "rent_price": "6100元/月",
        "area": "69㎡",
        "house_type": "2室1厅",
        "orientation": "南北",
        "floor": "中楼层/20层",
        "tags": ["电梯房", "近商圈"],
        "publish_time": "5天前",
    },
    {
        "source": "sample",
        "district": "丰台区",
        "community": "马家堡西里",
        "rent_price": "4700元/月",
        "area": "50㎡",
        "house_type": "1室1厅",
        "orientation": "西南",
        "floor": "高楼层/18层",
        "tags": ["近地铁"],
        "publish_time": "1天前",
    },
    {
        "source": "sample",
        "district": "通州区",
        "community": "新华联家园",
        "rent_price": "4300元/月",
        "area": "82㎡",
        "house_type": "2室1厅",
        "orientation": "南北",
        "floor": "低楼层/11层",
        "tags": ["整租", "有阳台"],
        "publish_time": "2天前",
    },
    {
        "source": "sample",
        "district": "通州区",
        "community": "梨园小镇",
        "rent_price": "5600元/月",
        "area": "105㎡",
        "house_type": "3室2厅",
        "orientation": "南",
        "floor": "中楼层/24层",
        "tags": ["电梯房", "适合家庭"],
        "publish_time": "今天",
    },
    {
        "source": "sample",
        "district": "昌平区",
        "community": "回龙观龙腾苑",
        "rent_price": "5900元/月",
        "area": "90㎡",
        "house_type": "3室1厅",
        "orientation": "南北",
        "floor": "中楼层/6层",
        "tags": ["近地铁", "整租"],
        "publish_time": "4天前",
    },
    {
        "source": "sample",
        "district": "昌平区",
        "community": "天通苑东一区",
        "rent_price": "3900元/月",
        "area": "58㎡",
        "house_type": "1室1厅",
        "orientation": "北",
        "floor": "高楼层/28层",
        "tags": ["电梯房"],
        "publish_time": "6天前",
    },
    {
        "source": "sample",
        "district": "大兴区",
        "community": "亦庄北岸",
        "rent_price": "5200元/月",
        "area": "76㎡",
        "house_type": "2室1厅",
        "orientation": "东南",
        "floor": "中楼层/15层",
        "tags": ["近地铁", "精装修"],
        "publish_time": "今天",
    },
    {
        "source": "sample",
        "district": "大兴区",
        "community": "黄村西里",
        "rent_price": "3600元/月",
        "area": "47㎡",
        "house_type": "1室1厅",
        "orientation": "东",
        "floor": "低楼层/6层",
        "tags": ["整租"],
        "publish_time": "8天前",
    },
    {
        "source": "sample",
        "district": "石景山区",
        "community": "古城南里",
        "rent_price": "4900元/月",
        "area": "65㎡",
        "house_type": "2室1厅",
        "orientation": "南",
        "floor": "中楼层/6层",
        "tags": ["交通便利"],
        "publish_time": "2天前",
    },
    {
        "source": "sample",
        "district": "石景山区",
        "community": "鲁谷小区",
        "rent_price": "6400元/月",
        "area": "91㎡",
        "house_type": "3室1厅",
        "orientation": "南北",
        "floor": "高楼层/18层",
        "tags": ["电梯房", "整租"],
        "publish_time": "7天前",
    },
    {
        "source": "sample",
        "district": "朝阳区",
        "community": "太阳宫新区",
        "rent_price": "11800元/月",
        "area": "112㎡",
        "house_type": "3室2厅",
        "orientation": "南北",
        "floor": "中楼层/26层",
        "tags": ["品质小区", "有车位"],
        "publish_time": "今天",
    },
    {
        "source": "sample",
        "district": "海淀区",
        "community": "五道口嘉园",
        "rent_price": "12200元/月",
        "area": "118㎡",
        "house_type": "3室2厅",
        "orientation": "南北",
        "floor": "高楼层/22层",
        "tags": ["近地铁", "适合合租"],
        "publish_time": "1天前",
    },
    {
        "source": "sample",
        "district": "西城区",
        "community": "马连道中里",
        "rent_price": "7200元/月",
        "area": "52㎡",
        "house_type": "1室1厅",
        "orientation": "南",
        "floor": "中楼层/14层",
        "tags": ["电梯房", "近地铁"],
        "publish_time": "3天前",
    },
    {
        "source": "sample",
        "district": "东城区",
        "community": "安定门外",
        "rent_price": "10800元/月",
        "area": "82㎡",
        "house_type": "2室1厅",
        "orientation": "东南",
        "floor": "中楼层/12层",
        "tags": ["整租", "集中供暖"],
        "publish_time": "2天前",
    },
]
